version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: acergiyen
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
